import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const MAX_SOURCE_BYTES = 1024 * 1024;
const DOWNLOAD_TIMEOUT_MS = 15_000;

function parseScriptInfo(script) {
  const header = script.replace(/^\uFEFF/, '').match(/^\s*\/\*[\s\S]*?\*\//)?.[0] ?? '';
  const field = (name, maxLength) => (header
    .match(new RegExp(`^\\s*\\*\\s*@${name}\\s+(.+?)\\s*$`, 'mi'))?.[1] ?? '')
    .replace(/[\u0000-\u001f\u007f]+/g, ' ')
    .trim()
    .slice(0, maxLength);
  return {
    name: field('name', 64),
    version: field('version', 128),
    author: field('author', 256)
  };
}

function renderDisabledModule() {
  return `// @ts-nocheck\n// Generated by cloudflare/scripts/prepare-lx.mjs. Do not edit.\n` +
    `export const bundledLxSource = { enabled: false, digest: '', name: '', version: '', author: '' } as const;\n` +
    `export function installBundledLxSource(_globalThis: any, _console: Console): void {}\n`;
}

function renderSourceModule(script, metadata) {
  const serialized = JSON.stringify(metadata);
  return `// @ts-nocheck\n// Generated by cloudflare/scripts/prepare-lx.mjs. Do not edit.\n` +
    `export const bundledLxSource = ${serialized} as const;\n` +
    `export function installBundledLxSource(globalThis: any, console: Console): void {\n` +
    `  const window = globalThis;\n` +
    `  const self = globalThis;\n` +
    `${script}\n` +
    `}\n`;
}

export async function prepareLxSource({
  sourceUrl = '',
  outputPath,
  fetchImpl = fetch
}) {
  if (!outputPath) throw new Error('outputPath is required');
  const normalizedUrl = String(sourceUrl || '').trim();
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  if (!normalizedUrl) {
    await fs.writeFile(outputPath, renderDisabledModule(), 'utf8');
    return { enabled: false, digest: '', name: '', version: '', author: '' };
  }

  const parsed = new URL(normalizedUrl);
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('CF_LX_SOURCE_URL must use http or https');
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), DOWNLOAD_TIMEOUT_MS);
  let response;
  try {
    response = await fetchImpl(parsed, {
      redirect: 'follow',
      signal: controller.signal,
      headers: { 'user-agent': 'wow-origin-cloudflare-builder/1.0' }
    });
  } finally {
    clearTimeout(timer);
  }
  if (!response.ok) throw new Error(`LX source download failed with HTTP ${response.status}`);
  const declaredLength = Number(response.headers.get('content-length') || 0);
  if (declaredLength > MAX_SOURCE_BYTES) throw new Error('LX source exceeds 1 MiB');

  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.byteLength > MAX_SOURCE_BYTES) throw new Error('LX source exceeds 1 MiB');
  const script = new TextDecoder().decode(bytes).replace(/^\uFEFF/, '');
  if (!script.trim()) throw new Error('LX source is empty');
  if (!/\.on\s*\(\s*[^,]*request|EVENT_NAMES\.request/.test(script)) {
    throw new Error('LX source does not appear to register a request handler');
  }
  if (!/\.send\s*\(\s*[^,]*inited|EVENT_NAMES\.inited/.test(script)) {
    throw new Error('LX source does not appear to send the inited event');
  }

  const info = parseScriptInfo(script);
  const metadata = {
    enabled: true,
    digest: crypto.createHash('sha256').update(bytes).digest('hex'),
    name: info.name,
    version: info.version,
    author: info.author
  };
  await fs.writeFile(outputPath, renderSourceModule(script, metadata), 'utf8');
  return metadata;
}

async function main() {
  const projectDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
  const outputPath = path.join(projectDirectory, 'cloudflare', 'generated', 'lx-source.ts');
  const result = await prepareLxSource({
    sourceUrl: process.env.CF_LX_SOURCE_URL || '',
    outputPath
  });
  const label = result.enabled
    ? `${result.name || '未命名源'} ${result.version || ''} (${result.digest.slice(0, 12)})`.trim()
    : '未配置';
  console.log(`[cloudflare] 洛雪全局源: ${label}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
